import type { CatalogItem } from "@/types/batops";

type CatalogSpec = Omit<CatalogItem, "id" | "organization_id" | "is_active" | "created_at">;

/**
 * Bibliothèque de prix de ClimAir Pro (prix HT).
 * Ces prix sont la seule source autorisée pour les devis, factures et suggestions IA.
 */
export const DEMO_CATALOG: CatalogSpec[] = [
  // ---- Main-d'œuvre -------------------------------------------------
  {
    reference: "MO-FRIG",
    name: "Main-d'œuvre technicien frigoriste / climatisation",
    category: "main_oeuvre",
    unit: "h",
    buying_price_ht: 38,
    selling_price_ht: 68,
    vat_rate: 10,
  },
  {
    reference: "MO-CHAU",
    name: "Main-d'œuvre plombier-chauffagiste",
    category: "main_oeuvre",
    unit: "h",
    buying_price_ht: 35,
    selling_price_ht: 62,
    vat_rate: 10,
  },
  {
    reference: "MO-ELEC",
    name: "Main-d'œuvre électricien",
    category: "main_oeuvre",
    unit: "h",
    buying_price_ht: 34,
    selling_price_ht: 60,
    vat_rate: 10,
  },
  // ---- Déplacement --------------------------------------------------
  {
    reference: "DEP-DIAG",
    name: "Forfait déplacement & diagnostic",
    description: "Déplacement dans un rayon de 30 km autour de Laxou et diagnostic de la panne.",
    category: "deplacement",
    unit: "forfait",
    buying_price_ht: 18,
    selling_price_ht: 59,
    vat_rate: 10,
  },
  {
    reference: "DEP-URG",
    name: "Majoration intervention urgente (soir & week-end)",
    category: "deplacement",
    unit: "forfait",
    buying_price_ht: 0,
    selling_price_ht: 80,
    vat_rate: 10,
  },
  // ---- Équipements --------------------------------------------------
  {
    reference: "PAC-ATL-8",
    name: "PAC Air/Eau Atlantic Alfea Extensa Duo R32 — 8 kW",
    description: "Pompe à chaleur air/eau bi-bloc avec ballon ECS 190 L intégré, classe A+++.",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 4950,
    selling_price_ht: 7150,
    vat_rate: 5.5,
    supplier_name: "Atlantic",
    equipment_template: {
      category: "pac_air_eau",
      brand: "Atlantic",
      model: "Alfea Extensa Duo R32 — 8 kW",
      refrigerant_type: "R32",
      warranty_years: 5,
    },
  },
  {
    reference: "CLIM-DAI-M35",
    name: "Climatisation mono-split Daikin Perfera FTXM35R — 3,5 kW",
    description: "Unité intérieure murale + groupe extérieur RXM35R, réversible, R32.",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 1020,
    selling_price_ht: 1690,
    vat_rate: 10,
    supplier_name: "Daikin",
    equipment_template: {
      category: "climatisation",
      brand: "Daikin",
      model: "Perfera FTXM35R + RXM35R",
      refrigerant_type: "R32",
      warranty_years: 5,
    },
  },
  {
    reference: "CLIM-DAI-M50",
    name: "Climatisation mono-split Daikin Perfera FTXM50R — 5,0 kW",
    description: "Unité intérieure murale + groupe extérieur RXM50R, réversible, R32.",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 1380,
    selling_price_ht: 2190,
    vat_rate: 10,
    supplier_name: "Daikin",
    equipment_template: {
      category: "climatisation",
      brand: "Daikin",
      model: "Perfera FTXM50R + RXM50R",
      refrigerant_type: "R32",
      warranty_years: 5,
    },
  },
  {
    reference: "CLIM-DAI-UE3",
    name: "Groupe extérieur multi-split Daikin 3MXM68A (3 sorties)",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 1690,
    selling_price_ht: 2590,
    vat_rate: 10,
    supplier_name: "Daikin",
    equipment_template: {
      category: "pac_air_air",
      brand: "Daikin",
      model: "3MXM68A — multi-split 3 sorties",
      refrigerant_type: "R32",
      warranty_years: 5,
    },
  },
  {
    reference: "CLIM-DAI-UI35",
    name: "Unité intérieure murale Daikin Perfera FTXM35R — 3,5 kW",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 420,
    selling_price_ht: 690,
    vat_rate: 10,
    supplier_name: "Daikin",
  },
  {
    reference: "CLIM-DAI-UI20",
    name: "Unité intérieure murale Daikin Perfera FTXM20R — 2,0 kW",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 340,
    selling_price_ht: 560,
    vat_rate: 10,
    supplier_name: "Daikin",
  },
  {
    reference: "CET-THE-200",
    name: "Chauffe-eau thermodynamique Thermor Aeromax 5 — 200 L",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 1540,
    selling_price_ht: 2150,
    vat_rate: 5.5,
    supplier_name: "Thermor",
    equipment_template: {
      category: "ballon_ecs",
      brand: "Thermor",
      model: "Aeromax 5 — 200 L",
      warranty_years: 5,
    },
  },
  {
    reference: "CHAU-VIE-25",
    name: "Chaudière gaz à condensation Viessmann Vitodens 100-W — 25 kW",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 1850,
    selling_price_ht: 2890,
    vat_rate: 10,
    supplier_name: "Viessmann",
    equipment_template: {
      category: "chaudiere",
      brand: "Viessmann",
      model: "Vitodens 100-W — 25 kW",
      warranty_years: 2,
    },
  },
  {
    reference: "RID-FRI-15",
    name: "Rideau d'air chaud électrique Frico AR3515 — 1,5 m",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 890,
    selling_price_ht: 1390,
    vat_rate: 20,
    supplier_name: "Frico",
    equipment_template: {
      category: "autre",
      brand: "Frico",
      model: "AR3515 — rideau d'air 1,5 m",
      warranty_years: 2,
    },
  },
  {
    reference: "VMC-ALD-250",
    name: "Caisson VMC collective Aldes VEC 250 MicroWatt",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 1980,
    selling_price_ht: 3150,
    vat_rate: 10,
    supplier_name: "Aldes",
    equipment_template: {
      category: "vmc",
      brand: "Aldes",
      model: "VEC 250 MicroWatt",
      warranty_years: 2,
    },
  },
  // ---- Pièces & accessoires -----------------------------------------
  {
    reference: "ACC-POMPE-SI27",
    name: "Pompe de relevage des condensats Sauermann Si-27",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 78,
    selling_price_ht: 136,
    vat_rate: 10,
    supplier_name: "Sauermann",
  },
  {
    reference: "ACC-LIAIS-38",
    name: "Liaison frigorifique cuivre isolée 1/4\" – 3/8\"",
    category: "fourniture",
    unit: "m",
    buying_price_ht: 9.8,
    selling_price_ht: 24,
    vat_rate: 10,
  },
  {
    reference: "ACC-LIAIS-12",
    name: "Liaison frigorifique cuivre isolée 1/4\" – 1/2\"",
    category: "fourniture",
    unit: "m",
    buying_price_ht: 12.5,
    selling_price_ht: 29,
    vat_rate: 10,
  },
  {
    reference: "ACC-GOUL",
    name: "Goulotte PVC de finition 80×60 (blanche)",
    category: "fourniture",
    unit: "m",
    buying_price_ht: 6.2,
    selling_price_ht: 14,
    vat_rate: 10,
  },
  {
    reference: "ACC-SUPP-AV",
    name: "Supports muraux + plots anti-vibratiles groupe extérieur",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 18,
    selling_price_ht: 45,
    vat_rate: 10,
  },
  {
    reference: "ACC-DISJ",
    name: "Protection électrique dédiée (disjoncteur 16/20 A + câblage)",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 32,
    selling_price_ht: 95,
    vat_rate: 10,
  },
  {
    reference: "ACC-POT-BOUE",
    name: "Pot à boue magnétique (filtre de désembouage) 1\"",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 64,
    selling_price_ht: 145,
    vat_rate: 10,
  },
  {
    reference: "ACC-KIT-HYD",
    name: "Kit de raccordement hydraulique PAC (vannes, flexibles, disconnecteur)",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 205,
    selling_price_ht: 443.52,
    vat_rate: 10,
  },
  {
    reference: "ACC-GS",
    name: "Groupe de sécurité NF + raccords diélectriques",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 38,
    selling_price_ht: 97.34,
    vat_rate: 10,
  },
  {
    reference: "ACC-VENT",
    name: "Kit ventouse concentrique 60/100 (sortie horizontale)",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 82,
    selling_price_ht: 185,
    vat_rate: 10,
  },
  {
    reference: "ACC-SONDE",
    name: "Sonde de température (thermistance) unité intérieure",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 14,
    selling_price_ht: 48,
    vat_rate: 10,
  },
  {
    reference: "ACC-CIRC-COLL",
    name: "Circulateur chaufferie collective Grundfos Magna3 32-80",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 1120,
    selling_price_ht: 1690,
    vat_rate: 10,
    supplier_name: "Grundfos",
  },
  {
    reference: "ACC-KIT-COL",
    name: "Kit réparation colonne (vanne 1/4 de tour, raccords laiton)",
    category: "fourniture",
    unit: "u",
    buying_price_ht: 68,
    selling_price_ht: 165,
    vat_rate: 10,
  },
  // ---- Forfaits -----------------------------------------------------
  {
    reference: "FOR-MES-R32",
    name: "Mise en service certifiée climatisation (tirage au vide, test azote, R32)",
    category: "forfait",
    unit: "forfait",
    buying_price_ht: 60,
    selling_price_ht: 190,
    vat_rate: 10,
  },
  {
    reference: "FOR-MES-PAC",
    name: "Mise en service PAC Air/Eau & paramétrage de la régulation",
    category: "forfait",
    unit: "forfait",
    buying_price_ht: 90,
    selling_price_ht: 320,
    vat_rate: 10,
  },
  {
    reference: "FOR-MES-VMC",
    name: "Mise en service VMC collective & mesures de débits",
    category: "forfait",
    unit: "forfait",
    buying_price_ht: 60,
    selling_price_ht: 240,
    vat_rate: 10,
  },
  {
    reference: "FOR-DESEMB",
    name: "Désembouage du réseau de chauffage (jusqu'à 10 radiateurs)",
    category: "forfait",
    unit: "forfait",
    buying_price_ht: 110,
    selling_price_ht: 520,
    vat_rate: 10,
  },
  {
    reference: "FOR-DEP-FIOUL",
    name: "Dépose chaudière fioul, neutralisation de cuve & évacuation des déchets",
    category: "forfait",
    unit: "forfait",
    buying_price_ht: 220,
    selling_price_ht: 780,
    vat_rate: 10,
  },
  {
    reference: "FOR-DEP-CE",
    name: "Dépose de l'ancien chauffe-eau & mise en déchetterie",
    category: "forfait",
    unit: "forfait",
    buying_price_ht: 25,
    selling_price_ht: 120,
    vat_rate: 10,
  },
  // ---- Contrats de maintenance --------------------------------------
  {
    reference: "MAINT-CLIM",
    name: "Contrat d'entretien annuel climatisation (1 unité)",
    category: "maintenance",
    unit: "forfait",
    buying_price_ht: 45,
    selling_price_ht: 150,
    vat_rate: 10,
  },
  {
    reference: "MAINT-PAC",
    name: "Contrat d'entretien annuel PAC Air/Eau",
    category: "maintenance",
    unit: "forfait",
    buying_price_ht: 60,
    selling_price_ht: 210,
    vat_rate: 10,
  },
  {
    reference: "MAINT-PRO",
    name: "Contrat d'entretien climatisation professionnelle (gainable + rideau d'air)",
    category: "maintenance",
    unit: "forfait",
    buying_price_ht: 120,
    selling_price_ht: 380,
    vat_rate: 20,
  },
  {
    reference: "MAINT-VMC",
    name: "Contrat d'entretien VMC collective (par résidence)",
    category: "maintenance",
    unit: "forfait",
    buying_price_ht: 90,
    selling_price_ht: 290,
    vat_rate: 10,
  },
];

export function catalogIdFor(reference: string): string {
  return `cat_${reference.toLowerCase().replace(/[^a-z0-9]+/g, "_")}`;
}
